### ISSUE TITLE
Add Java / Maven support

### ISSUE THREAD

**Issue by jordanpadams** [NASA-PDS/roundup-action#1]

**Comment by tloubrieu-jpl** [comment]
@nutjob4life do you need one more sprint to work on this ?

**Comment by nutjob4life** [comment]
Snapshot artifacts work fine with just a username and password; but for ops releases OSSRH requires a GPG key. See

- https://osr.jpl.nasa.gov/wiki/pages/viewpage.action?spaceKey=PDSEN&title=Open+Sourcing+Software#OpenSourcingSoftware-PrepForMavenCentralDeployment
- https://central.sonatype.org/pages/apache-maven.html#gpg-signed-components
