### ISSUE TITLE
unstable build failed

### ISSUE THREAD

**Issue by tloubrieu-jpl** [NASA-PDS/roundup-action#103]
## 🐛 Describe the bug

See action https://github.com/NASA-PDS/registry-crawler-service/actions/runs/3687311354

The snapshot release is done and accessible but on different url, see https://github.com/NASA-PDS/registry-crawler-service/releases/download/untagged-066a2eae3757652aed44/registry-crawler-service-1.1.0-SNAPSHOT-bin.tar.gz compared to what roundup is looking for, see https://github.com/NASA-PDS/registry-crawler-service/releases/download/v1.1.0-SNAPSHOT/registry-crawler-service-1.1.0-SNAPSHOT-bin.tar.gz

**Comment by nutjob4life** [comment]
The workflow that had the problem wasn't a Roundup Action workflow, though. It was the Imaging workflow. I believe to fix this in `registry-crawler-api` we need [a fix similar to this one](https://github.com/NASA-PDS/registry-api/pull/205/files).

**Comment by nutjob4life** [comment]
Issue moved to [NASA-PDS/registry-crawler-service #26](https://github.com/NASA-PDS/registry-crawler-service/issues/26) via [**Zenhub**](https://www.zenhub.com/)
