### ISSUE TITLE
Roundup broken for python repos

### ISSUE THREAD

**Issue by jordanpadams** [NASA-PDS/roundup-action#105]
## 📜 To Reproduce
https://github.com/NASA-PDS/sumo-tools/actions/runs/3953533728/jobs/6769903121

## 🕵️ Expected behavior

Tags a new version

I tried this with both of these tags:
* `release/0.2.0`
* `release/v0.2.0`

**Comment by jimmie** [comment]
will escalate due to severity

**Comment by tloubrieu-jpl** [comment]
Might be solved by #106

**Comment by tloubrieu-jpl** [comment]
3 PR need to be reviewed to fix this ticket

**Comment by nutjob4life** [comment]
Turns out it was just 2 PRs:

- https://github.com/NASA-PDS/pds-github-util/pull/71
- https://github.com/NASA-PDS/roundup-action/pull/107
