### ISSUE TITLE
Missing snapshot tag cleanup prior to new unstable release

### ISSUE THREAD

**Issue by jordanpadams** [NASA-PDS/roundup-action#11]
**Describe the bug**
The SNAPSHOT releases are being recreated for each unstable CI/CD run, but the tags are not being cleaned up. This causes the tags and release assets to get out of sync.

**To Reproduce**
See [latest validate snapshot](https://github.com/NASA-PDS/validate/releases/tag/1.25.0-SNAPSHOT). 

It says `@pdsen-ci pdsen-ci released this 6 minutes ago` but then follows with `7 commits to master since this release` indicating a new tag was not created with the new release

**Proposed Fixes**

Java:
```
    - name: Clean previous dev/snapshot tags
      run: |
        git fetch --prune --unshallow --tags
        git tag -l | grep 'SNAPSHOT' | xargs -t -I arg sh -c 'git tag -d arg;git push --delete origin arg;'
```

Python (haven't tested this with Python, but assuming it has the same issue?):
```
    - name: Clean previous dev/snapshot tags
      run: |
        git fetch --prune --unshallow --tags
        git tag -l | grep 'dev' | xargs -t -I arg sh -c 'git tag -d arg;git push --delete origin arg;'
```

**Comment by nutjob4life** [comment]
Unfortunately, when I tried `git fetch --prune --unshallow --tags` I get an error:

    fatal: --unshallow on a complete repository does not make sense

I'm not sure what this means.

See:

- https://github.com/NASA-PDS/roundup-action/blob/master/src/pds/roundup/_maven.py#L164
- https://github.com/NASA-PDS/roundup-action/blob/master/src/pds/roundup/_python.py#L97

**Comment by nutjob4life** [comment]
Further research: in my test environment, I do plain `git clone` during testing while the [checkout action(https://github.com/actions/checkout) only clones the ref that triggered the workflow.

Pressing on!

**Comment by nutjob4life** [comment]
Ah I think I found the problem.

In Python I'm filtering for `*dev*` but in Maven I copied the same logic over when I should be looking for `*SNAPSHOT*`

(Also FYI, no need to pipe `git tag -l` into `grep` since it has filtering capability built-in.)

**Comment by jordanpadams** [comment]
@nutjob4life this unfortunately doesn't look to be fixed. see latest build of validate.

 
<img width="809" alt="Screen Shot 2020-11-18 at 2 44 49 PM" src="https://user-images.githubusercontent.com/33492486/99597342-b3a54a80-29ac-11eb-88b4-3ab731ea0ed2.png">

**Comment by jordanpadams** [comment]
@nutjob4life unfortunately, it still doesn't look like this has been fixed?

https://github.com/NASA-PDS/validate/releases/tag/1.25.0-SNAPSHOT

**Comment by tloubrieu-jpl** [comment]
@nutjob4life needs to update the docker image with git-lfs

**Comment by nutjob4life** [comment]
Here's where I think the issue is:
![Screen Shot 2020-12-08 at 2 27 38 PM](https://user-images.githubusercontent.com/814813/101537725-976c4c00-3961-11eb-96b4-9af736f9b854.png)

**Comment by nutjob4life** [comment]
Okay, updated [the base image](https://hub.docker.com/r/nasapds/pds-github-actions-base) with `git-lfs` and re-ran [the action](https://github.com/NASA-PDS/validate/runs/1519973847?check_suite_focus=true) on [validate](https://github.com/NASA-PDS/validate/). Here's a screenshot of the step now:

![Screen Shot 2020-12-08 at 4 21 38 PM](https://user-images.githubusercontent.com/814813/101548572-b1158f80-3971-11eb-9ab6-28deb11d4218.png)

Does that look like it fixed it @jordanpadams?

**Comment by jordanpadams** [comment]
🎉 looks good @nutjob4life. let me see what else I can break...
