### ISSUE TITLE
Roundup pushes version update prior to completion of execution

### ISSUE THREAD

**Issue by jordanpadams** [NASA-PDS/roundup-action#124]
### Checked for duplicates

No - I haven't checked

### 🐛 Describe the bug

A tag of a release that failed on upload to Maven central, the version increment was still committed to main.

### 🕵️ Expected behavior

I expected the push to main would be one of the last steps of the process. The version increment needs to happen early on, but the commit of the version update is not needed until the last step after everything was successful.

### 📜 To Reproduce

Try to build a java repo and see it fail.

Exhibit A: https://github.com/NASA-PDS/transform/actions/runs/6630418254
With push even with the failure: https://github.com/NASA-PDS/transform/actions/runs/6631314379

### 🦄 Related requirements

🦄 #xyz

**Comment by nutjob4life** [comment]
Note that this is still in progress and [pull request № 126](https://github.com/NASA-PDS/roundup-action/pull/126) referenced above is a pre-requisite to a forthcoming pull request.

**Comment by gxtchen** [comment]
@jordanpadams @nutjob4life Can I test this in my testing environment?

**Comment by jordanpadams** [comment]
@gxtchen you can skip this
