### ISSUE TITLE
Improve logging dump from roundup run

### ISSUE THREAD

**Issue by jordanpadams** [NASA-PDS/roundup-action#13]
**Is your feature request related to a problem? Please describe.**
pds4-jparser is not building properly, but not sure what the issue is:

https://github.com/NASA-PDS/pds4-jparser/runs/1414372832?check_suite_focus=true#step:4:27

```
DEBUG:pds.roundup.util:🏃‍♀️ Running «['mvn', 'test']»
CRITICAL:pds.roundup.util:💥 Process with command line ['mvn', 'test'] failed with status 1
CRITICAL:pds.roundup.util:📚 Stderr = «b''»
```

**Comment by jordanpadams** [comment]
@nutjob4life what version of Java is being used in this repo? We may need to be able to specify a java version. pds4-jparser may not be able to use java11+

**Comment by nutjob4life** [comment]
@jordanpadams the version of Java is [openjdk11-jdk](https://pkgs.alpinelinux.org/package/edge/community/x86_64/openjdk11-jdk).
