### ISSUE TITLE
Unstable Pipeline failing with unsatisfiable install dependency on Data Upload Manager repository

### ISSUE THREAD

**Issue by collinss-jpl** [NASA-PDS/roundup-action#139]
### Checked for duplicates

No - I haven't checked

### 🐛 Describe the bug

Upon merging a branch (that was passing Branch Integration Testing) in the DUM repo, the "Unstable" workflow failed due to an unsatisfiable installation dependency when installing roundup itself.

Build details can be found here: https://github.com/NASA-PDS/data-upload-manager/actions/runs/10014873400/job/27685384518#step:2:257

### 🕵️ Expected behavior

Unstable pipeline to build successfully

### 📜 To Reproduce

Run the Unstable pipeline for a branch merged to the DUM repository

### 📚 Version of Software Used

stable

**Comment by jordanpadams** [comment]
@nutjob4life any idea what might be going on here or how I can test this?

**Comment by nutjob4life** [comment]
@jordanpadams you can see the problem [on this line](https://github.com/NASA-PDS/roundup-action/blob/799795beb3e7dec9ad28484b12b282c51da708a4/Dockerfile#L30):

    pip install install /usr/src/roundup

The word `install` is duplicated.

**Comment by nutjob4life** [comment]
@jordanpadams thanks for the quick PR; approved and merged

I also moved the `stable` tag post-merge so all repos can benefit

**Comment by jordanpadams** [comment]
Skipping I&T. Internal build bug
