### ISSUE TITLE
Roundup failing on tagging stable release for pds4-information-model

### ISSUE THREAD

**Issue by jordanpadams** [NASA-PDS/roundup-action#142]
### Checked for duplicates

Yes - I've already checked

### 🐛 Describe the bug

When I tried to tag a new release, I am getting an error. https://github.com/NASA-PDS/pds4-information-model/actions/runs/11757269747/job/32754333055

### 🕵️ Expected behavior

I expected the repo to be tagged and released

### 📜 To Reproduce

https://github.com/NASA-PDS/pds4-information-model/actions/runs/11757269747/job/32754333055

```
CRITICAL:pds.roundup.util:📚 Stderr = «fatal: No names found, cannot describe anything.
»
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/pds/roundup/util.py", line 62, in invoke
    cp = subprocess.run(argv, stdin=subprocess.DEVNULL, capture_output=True, check=True)
  File "/usr/local/lib/python3.9/subprocess.py", line 528, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['git', 'describe', '--tags', '--abbrev=0', '--match', 'release/*']' returned non-zero exit status 128.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/bin/roundup", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.9/site-packages/pds/roundup/main.py", line 119, in main
    _assemblies[args.assembly](context).roundup()
  File "/usr/local/lib/python3.9/site-packages/pds/roundup/assembly.py", line 42, in roundup
    step.execute()
  File "/usr/local/lib/python3.9/site-packages/pds/roundup/_maven.py", line 250, in execute
    self._tag_release()
  File "/usr/local/lib/python3.9/site-packages/pds/roundup/_maven.py", line 214, in _tag_release
    tag = invokeGIT(['describe', '--tags', '--abbrev=0', '--match', 'release/*']).strip()
  File "/usr/local/lib/python3.9/site-packages/pds/roundup/util.py", line 101, in invokeGIT
    return invoke(argv)
  File "/usr/local/lib/python3.9/site-packages/pds/roundup/util.py", line 71, in invoke
    raise InvokedProcessError(ex)
pds.roundup.errors.InvokedProcessError: ('Process %s failed with code %d', ['git', 'describe', '--tags', '--abbrev=0', '--match', 'release/*'], 128)
```

### 🖥 Environment Info

GitHub Action env

**Comment by nutjob4life** [comment]
@jordanpadams trying to reproduce it in the sandbox

**Comment by jordanpadams** [comment]
@nutjob4life any status on this one?

**Comment by nutjob4life** [comment]
@jordanpadams, just figured it out! I'm writing it up

**Comment by nutjob4life** [comment]
@jordanpadams this should now be fixed. In the end, I had to generate a new username + token pair (apparently the UI at https://central.sonatype.com/account is the wrong one, it gives only a token—we need to use https://oss.sonatype.org/#profile;User%20Token which generates both a token username and a token password)

See a successful run in the sandbox at: https://github.com/nasa-pds-engineering-node/pds4-information-model/actions/runs/11881545051

I've set the new OSSRH_USERNAME and OSSRH_PASSWORD in both of our organizations

That being said, I do recommend updating pom.xml so that it uses the latest parent pom; I'll be submitting a PR for that shortly

**Comment by jordanpadams** [comment]
@nutjob4life very odd. thanks for tracking this down.

**Comment by nutjob4life** [comment]
@jordanpadams you're welcome! Let me know if it still fails outside of the sandbox.

(Even more suspicious: the new UI for tokens has a button for "Access User Token", saying it will display your current token username and token password, _but_ it will create one if it doesn't exist. When I pressed this, it said it was _generating_ the token! Meaning whatever token we had in the past was no longer being honored.

Combined with getting reverted from s01.oss.sonatype.org back to oss.sonatype.org, I have no clue what happened in the last three weeks—and `pdsen-ci@jpl.nasa.gov` has no email noticed regarding it either.)

**Comment by nutjob4life** [comment]
@jordanpadams currently having some popcorn while watching https://github.com/NASA-PDS/pds4-information-model/actions/runs/11881723126/job/33106383535 😬 

Argh it failed!

But not for the reason mentioned in this issue 😅

**Comment by jordanpadams** [comment]
@nutjob4life round 2:

https://github.com/NASA-PDS/pds4-information-model/actions/runs/11883727105

**Comment by jordanpadams** [comment]
the problem was part of the deployment was successful for 15.2.0 the first go around, which included pushing to Maven Central, so it now won't let me try to push that again. Trying again with 15.2.2, which we have never tried before, and should give us a fresh run.

**Comment by nutjob4life** [comment]
@jordanpadams it's great to see green ✅
