### ISSUE TITLE
Override the maven goal sequence with a with: mvn-goals option

### ISSUE THREAD

**Issue by tloubrieu-jpl** [NASA-PDS/roundup-action#23]
Sometime the repository use specific plugins which requires specific goals to be activiated.

For example:
https://github.com/NASA-PDS/api-search-query-lexer

Is build with sequence:

mvn clean antlr4:antlr4 deploy

We want to add an option:

with:
   mvn-goals: clean antlr4:antlr4 deploy

Which will override the current default goals sequence

**Comment by nutjob4life** [comment]
Re-opened; see https://github.com/NASA-PDS/roundup-action/pull/30

**Comment by tloubrieu-jpl** [comment]
@nutjob4life can possibly revert to the preivous status where it worked.
