### ISSUE TITLE
Java documentation is empty when attached to repo

### ISSUE THREAD

**Issue by jordanpadams** [NASA-PDS/roundup-action#36]
**Describe the bug**
- [ ] See https://github.com/NASA-PDS/pds-registry-app/releases/download/v0.3.0-SNAPSHOT/documentation.zip . It's empty but the site docs do exist.

- [ ] Additionally, see https://github.com/NASA-PDS/pds-registry-app/releases/download/v0.3.0/documentation.zip . should this documentation be attached to the stable releases as well? I am OK with it, but just wondering if this is because we are kicking off the unstable / stable releases at the same time

**Comment by tloubrieu-jpl** [comment]
it blocked by pull request NASA-PDS/pds-template-repo-java#8
