### ISSUE TITLE
snapshot release of registry-api-service fails on changelog generator

### ISSUE THREAD

**Issue by tloubrieu-jpl** [NASA-PDS/roundup-action#38]
## 🐛 Describe the bug

The changelog update fails.
See action https://github.com/NASA-PDS/registry-api-service/runs/2289485427?check_suite_focus=true

## 📜 To Reproduce
Replay action https://github.com/NASA-PDS/registry-api-service/runs/2289485427?check_suite_focus=true

## 🕵️ Expected behavior
The snapshot release should be generated.

## 📚 Version of Software Used
I think there was a similar bug in the changelog tool stable releases and I needed to work from a specific commit version to make it work. 

## 🩺 Test Data / Additional context

** :unicorn: Applicable requirements**

**Comment by tloubrieu-jpl** [comment]
The bug might be linked to #29

**Comment by tloubrieu-jpl** [comment]
@nutjob4life for this line https://github.com/NASA-PDS/github-actions-base/blob/a33ea4f9f7f9a9bc24651aa661af2325ee4fdb7e/Dockerfile#L60

I used to get a specific commit instead of a stable release, because there was a correction the developers made which was not available in the tool. I will check that (there was a ticket in their repo for that error)

**Comment by jordanpadams** [comment]
@tloubrieu-jpl this is a problem with changelog generator. i just had a ticket to fix that. https://github.com/NASA-PDS/github-actions-base/issues/1 . that commit does not appear to work anymore (or at least I have not been able to get it to work for some time with validate / pds4-jparser / pds4-information-model)

```
github_changelog_generator --user NASA-PDS --project $repo_short_name  \
                           --output CHANGELOG.md --token $GITHUB_TOKEN \
                           --configure-sections '{"requirements":{"prefix":"**Requirements:**","labels":["requirement"]},"improvements":{"prefix":"**Improvements:**","labels":["enhancement"]},"defects":{"prefix":"**Defects:**","labels":["bug"]}}' \
                           --no-pull-requests --issues-label '**Other closed issues:**' \
                           --exclude-labels "wontfix", "duplicate", "invalid","theme" \
                           --future-release v$new_version
```

**Comment by nutjob4life** [comment]
This looks to be addressed with the merge of https://github.com/NASA-PDS/github-actions-base/pull/4 but also N.B. that the Github Actions Base image is now live at https://hub.docker.com/r/nasapds/pds-github-actions-base meaning that the next run of a workflow shall include the reversion of the change to github-changelog-generator such that it again uses the specific commit 322e30a78115ab948e358cd916a9f78e55fe21c1
