### ISSUE TITLE
Update CHANGELOG generation run to use older version of changelog generator v1.15.2

### ISSUE THREAD

**Issue by jordanpadams** [NASA-PDS/roundup-action#39]
## 🐛 Describe the bug

See See https://github.com/NASA-PDS/roundup-action/issues/38 for bug 
and https://github.com/NASA-PDS/roundup-action/issues/38#issuecomment-815079997 for resolution

**Comment by nutjob4life** [comment]
See https://github.com/NASA-PDS/github-actions-base/pull/4 and note that the Github Actions Base image is already live at https://hub.docker.com/r/nasapds/pds-github-actions-base so the next run of a workflow will have the update that reverted the change to github-changelog-generator change to use the specific commit 322e30a78115ab948e358cd916a9f78e55fe21c1
