### ISSUE TITLE
stable java Roundup fails if folder target/staging is not available (used for documentation)

### ISSUE THREAD

**Issue by tloubrieu-jpl** [NASA-PDS/roundup-action#44]
## 🐛 Describe the bug

See for example https://github.com/NASA-PDS/pds-api-javalib/runs/2632549207?check_suite_focus=true

## 📜 To Reproduce
Create tag on repository https://github.com/NASA-PDS/pds-api-javalib

## 🕵️ Expected behavior

That should work with documentation created in target/apidocs

We can set an environment varialbe for that ?

## 🖥 System Info

---

** :unicorn: Applicable requirements**

**Comment by jordanpadams** [comment]
@tloubrieu-jpl i think we should keep `target/staging` as a default and then make this an optional argument?
