### ISSUE TITLE
roundup action unstable releases appear to be unstable

### ISSUE THREAD

**Issue by jordanpadams** [NASA-PDS/roundup-action#52]
## 🐛 Describe the bug

1. unstable releases are being tagged as stable releases
2. past unstable releases are not being cleaned up from the repo

## 📜 To Reproduce
1. See https://github.com/NASA-PDS/pds-template-repo-python/releases/latest points to a dev release generated by [this unstable CICD action](https://github.com/NASA-PDS/pds-template-repo-python/actions/runs/1046151284)
2. See https://github.com/NASA-PDS/pds-template-repo-python/releases for all the past dev releases included (oops! i cleaned these up... but trust me. it happens)

## 🕵️ Expected behavior

1. Unstable releases should be tagged as `Pre-Release` and, for python, maybe renamed to something cleaner (is there something standard others use)?
2. Cleanup of old dev releases - Up for discussion. I see both sides of this. Having all past tagged versions is great for complete transparency. maybe we only cleanup at each stable release (or if the tag already exists)?

**Comment by MJJoyce** [comment]
unstable releases look like they're being properly marked as `SNAPSHOT` at the moment:
https://github.com/NASA-PDS/pds-github-util/releases

That was addressed [here](https://github.com/NASA-PDS/roundup-action/issues/57) and in the linked ticket.

Currently it looks like the snapshot releases are being removed as we expect but tags are not. See here:
![Screen Shot 2021-09-16 at 14 06 23](https://user-images.githubusercontent.com/860902/133686249-43a43757-7beb-4c3e-bea0-a140b6a3fefe.png)

I imagine we'll want those stripped out.

**Comment by MJJoyce** [comment]
Note, after #62 / #63 are merged I think (please don't jinx it, please don't jinx it) that this can be marked as resolved.

**Comment by nutjob4life** [comment]
Issue #62 is closed and #63 is merged so closing 🤞
