### ISSUE TITLE
As a developer, I want Python packages to be distributed as wheels

### ISSUE THREAD

**Issue by MJJoyce** [NASA-PDS/roundup-action#55]
Some of our builds ran into an issue when attempting to install `pds-github-utils` from a `tar.gz` archive. See NASA-PDS/pds-github-util#25 for additional details on the root cause.

From that discussion there we figured that we should update our package releases to only push wheels instead of both. So ... let's do that!

**Comment by nutjob4life** [comment]
Hi folks, maybe we can mark this one as `wontfix` or `cannot-reproduce`?

The Roundup Action builds Python distributions in two places in the code (one for unstable, one for stable):

1. https://github.com/NASA-PDS/roundup-action/blob/eb91559134337cdd7be11694d8d55355d0fa1db2/src/pds/roundup/_python.py#L91
2. https://github.com/NASA-PDS/roundup-action/blob/eb91559134337cdd7be11694d8d55355d0fa1db2/src/pds/roundup/_python.py#L96

and in both of those spots you can see it uses the setuptools `bdist_wheel` command to make wheels, not `sdist` tarballs or zips.

The issue references [pds-github-util](https://github.com/NASA-PDS/pds-github-util) as having a problem with `.tar.gz` distributions, specifically version 0.23.0. On PyPI, sure enough:

![Screen Shot 2021-09-09 at 10 44 57 AM](https://user-images.githubusercontent.com/814813/132718904-713666a1-ae5b-435a-95dd-5a6f60635b85.png)

But starting with 0.24.0, we have a wheel:

![Screen Shot 2021-09-09 at 10 47 09 AM](https://user-images.githubusercontent.com/814813/132719014-57bffa52-7484-4baa-9b69-a6f8b6b93e31.png)

And the current "Squaredown" workflow for `pds-github-util` is producing wheels; see https://github.com/NASA-PDS/pds-github-util/blob/c1aedd46d76ff5354363742f0bc6b2f743e6dad2/.github/workflows/squaredown-stable.yaml#L63

So maybe this is a non-issue? 🤷‍♀️

**Comment by MJJoyce** [comment]
+1, I agree that this is a non-issue. Closing it out!
