### ISSUE TITLE
As a developer, I want to Roundup new repositories too

### ISSUE THREAD

**Issue by nutjob4life** [NASA-PDS/roundup-action#56]
The Roundup workflows recently got added to the `archive-analytics` repository. This repository has never had a release before. When the Roundup got to it, though, [it failed with this log](https://github.com/NASA-PDS/archive-analytics/runs/3537026275?check_suite_focus=true).

The issue seems to be:

1. The Roundup build step finds there's no prior releases, so Versioneer can't make a `vX.Y.Z` style release tag. So no distribution gets made.
2. Later, the Roundup's artifact publication step tries to publish any distribution made from the build step. But there's none.

Two alternatives:

1. Assume that in a new repository the starting version number shall be `v0.0.0`.
2. Don't make assumptions; new repositories will skip artifact publication until a human being sets an initial version with a `release/X.Y.Z` branch

**Comment by jordanpadams** [comment]
I vote for option 1, v0.0.0

**Comment by jordanpadams** [comment]
tabling this as a low priority since there is a pretty easy workaround we can do

**Comment by nutjob4life** [comment]
Woops, I just saw the low priority marker on this. Sorry!

Well got a solution anyway 😅
