### ISSUE TITLE
We can't use "SNAPSHOT" in Python packaging

### ISSUE THREAD

**Issue by nutjob4life** [NASA-PDS/roundup-action#66]
## 🐛 Describe the bug

Argh, I thought this was familiar! Too much to keep track of! Despite all the effort we put into #62 we can't use `SNAPSHOT` in Python packaging; see https://github.com/NASA-PDS/pds-doi-service/runs/3670410132?check_suite_focus=true#step:6:1040 for an example.

See https://www.python.org/dev/peps/pep-0440/#public-version-identifiers … we can have `dev`, but no snapshot.

**Comment by MJJoyce** [comment]
![Darth_Vader_Noooo_Banner](https://user-images.githubusercontent.com/860902/134374876-f173740d-1871-4ba4-95af-f4540a510f2a.jpg)

**Comment by MJJoyce** [comment]
Note, in addition the updates in NASA-PDS/pds-github-util#44 we need to revert the naming changes from #61 and #63
