### ISSUE TITLE
Revise how versions are bumped up

### ISSUE THREAD

**Issue by tloubrieu-jpl** [NASA-PDS/roundup-action#77]
The current PDS workflow for stable release when new features are developed is:

1. release vX.Y.0
2. create snapshot for vX.Y+1.0 when new features are going to be developed.

If critical bug are found on release vX.Y.0, then updates will be done on branch release/X.Y and a new stable release tagged vX.Y.1 will be published.

The bug commit can also be cherry-pick to or from the main branch.

This need to be discussed since there might be other options.

**Comment by jordanpadams** [comment]
@tloubrieu-jpl let's talk about this at the breakout. I would like to discuss the priority of this issue and if procedural workarounds are possible.

**Comment by jordanpadams** [comment]
closing as wontfix. per some conversations on slack, we decided to create branches for each version
