### ISSUE TITLE
Roundup still using nasa-pds-engineering-node pds-github-util

### ISSUE THREAD

**Issue by jordanpadams** [NASA-PDS/roundup-action#78]
## 🐛 Describe the bug

See https://github.com/NASA-PDS/pds-registry-common/runs/4769193173?check_suite_focus=true#step:2:67

<img width="1273" alt="Screen Shot 2022-01-10 at 4 33 08 PM" src="https://user-images.githubusercontent.com/33492486/148860747-38f1f575-eae6-4497-96d0-7584fa25bf49.png">

It looks like we are trying to clone pds-github-util instead of install with pip and it is failing in all repos with error about deprecated git commands

**Comment by nutjob4life** [comment]
There are actually three things happening here:

1. We're not `git clone`ing `pds-github-util`; we are indeed `pip install`ing it, but using this command:
```
pip install 'git+git://github.com/NASA-PDS/pds-github-util@stable#egg=pds_github_util'
```
2. However, effective 2022-01-11, the `git://` protocol [became unsupported](https://github.blog/2021-09-01-improving-git-protocol-security-github/#no-more-unauthenticated-git) when used unencrypted but even when completely internal to GitHub.
3. The `roundup-action@stable` is one commit behind `roundup-action@main` and contains a reference to `nasa-pds-engineering-node` (the sandbox).

I'll tackle these momentarily—but first: ☕️😅

**Comment by nutjob4life** [comment]
Since this is absolutely critical and is what I hope will be a one-line fix, I'm going to exercise "executive privilege" and commit this directly to `main` & `stable`.

The fix is to change this:
```
pip install 'git+git://github.com/NASA-PDS/pds-github-util@stable#egg=pds_github_util'
```
to this:
```
pip install 'git+https://github.com/NASA-PDS/pds-github-util@stable#egg=pds_github_util'
```

**Comment by jordanpadams** [comment]
Looks to have worked. Thanks @nutjob4life !

**Comment by nutjob4life** [comment]
![awkward-dance-awkward](https://user-images.githubusercontent.com/814813/148971845-15bd6474-2938-44fa-9502-1d60fc6cf93b.gif)
