### ISSUE TITLE
Roundup doesn't generate sphinx-argparse docs

### ISSUE THREAD

**Issue by nutjob4life** [NASA-PDS/roundup-action#79]
## 🐛 Describe the bug

@collinss-jpl reports that `release/2.1.2` of the `pds-doi-serivce` worked fine but https://nasa-pds.github.io/doi-service/api/index.html didn't include any argparse docs.

This could be that Roundup is executing `sphinx-build` in its own context instead of in the rounded-up package's venv. Although the preparation step does set the `PATH` appropriately so that if there's a `sphinx-build` in the venv it should be happening. Odd.

## 🕵️ Expected behavior

`sphinx-argparse` as well as any other Sphinx add-ons (like `sphinxcontrib-napoleon`) should be supported.

**Comment by collinss-jpl** [comment]
@nutjob4life Just combed over the Roundup log and noticed this here: https://github.com/NASA-PDS/doi-service/runs/4810121150?check_suite_focus=true#step:6:527

```
DEBUG:pds.roundup.util:Stderr = «/github/workspace/docs/source/api/index.rst:9: WARNING: Failed to import "create_parser" from "pds_doi_service.core.actions.action".
No module named 'pds_doi_service'
/github/workspace/docs/source/api/index.rst:17: WARNING: Failed to import "create_cmd_parser" from "pds_doi_service.core.util.initialize_production_deployment".
No module named 'pds_doi_service'
```

Could this be as simple as making sure the local checkout of the service is added to Roundup's `PYTHONPATH`?
