### ISSUE TITLE
Update SNAPSHOT / DEV versioning to always increment minor version

### ISSUE THREAD

**Issue by jordanpadams** [NASA-PDS/roundup-action#81]
## 💡 Description

Right now, roundup is incrementing the bug version,

now:
```
1.2.0-SNAPSHOT -> 1.2.0 -> 1.2.1-SNAPSHOT - minor release
1.2.1-SNAPSHOT -> 1.2.1 -> 1.2.2-SNAPSHOT - patch
1.2.2-SNAPSHOT -> 1.3.0 -> 1.3.1-SNAPSHOT - minor release
```

desired
```
1.2.0-SNAPSHOT -> 1.2.0 -> 1.3.0-SNAPSHOT - minor release
1.3.0-SNAPSHOT -> 1.2.1 -> 1.3.0-SNAPSHOT - patch
1.3.0-SNAPSHOT -> 1.3.0 -> 1.3.0-SNAPSHOT - minor release
```

rationale being when I thing about `major.minor.patch` I consider ongoing work to be going towards the a new `major`/`minor` version with new enhancements and development. Whereas `patch` is more of a hotfix version that only really pops up sporadically for bug fixes. This way a user can always loop in to `1.3.0-SNAPSHOT` to get the latest snapshot updates until it is explicitly versioned.

My two cents anyways...

**Comment by nutjob4life** [comment]
Awaiting review; see https://github.com/NASA-PDS/roundup-action/pull/83
