### ISSUE TITLE
roundup versioning not working properly on nested maven repositories

### ISSUE THREAD

**Issue by tloubrieu-jpl** [NASA-PDS/roundup-action#82]
## 🐛 Describe the bug

per https://github.com/NASA-PDS/pds4-information-model/runs/6067059849?check_suite_focus=true#step:5:209, this error occurs when the top-level POM version number is changed, but the lower level POM versions are not updated.

## 📜 To Reproduce
1. Fork / clone pds4-information-model repo into sandbox
2. 
```
git checkout -b release/14.0.1
git push origin release/14.0.1
```
3. see error above

As a workaround, after deleting the original branch, I manually versioned the repo and it worked:
```
git checkout -b release/14.0.1
mvn versions:set -DnewVersion=14.0.1
git add pom.xml
git add */pom.xml
git commit -m "Prep for v14.0.1 release"
git push origin release/14.0.1
```
And it worked as expected. However, [per this commit](https://github.com/NASA-PDS/pds4-information-model/commit/4da5e1adf043a7d8fa5eca250efc1e819eb7ff0c) roundup only versioned the top-level POM when transitioning back to SNAPSHOT, so the unstable build is now failing.

Other info:
* [Commit for manual versioning here](457faad173fbaf26a48f956049e929406a99d5b7)
* [Roundup's empty commit since the versioning was already done](9fda25854d89d05b94377f899da495774d5b402d)

## 🕵️ Expected behavior

Versions properly

## 🖥 System Info

---

**Comment by nutjob4life** [comment]
@jordanpadams thanks for the incredibly thorough report. Tells me _precisely_ what to fix.
