### ISSUE TITLE
Roundup does not fail on error

### ISSUE THREAD

**Issue by jordanpadams** [NASA-PDS/roundup-action#85]
## 🐛 Describe the bug

Per https://github.com/NASA-PDS/pds4-information-model/runs/6815107257?check_suite_focus=true#step:5:120, this should fail but it claims to complete successfully.

## 📜 To Reproduce
See https://github.com/NASA-PDS/pds4-information-model/runs/6815107257?check_suite_focus=true#step:5:120

## 🕵️ Expected behavior

Release should fail

**Comment by nutjob4life** [comment]
@jordanpadams I think this is a bug in Maven—or it really _was successful_.

Looking [at the log file at the line specified](https://github.com/NASA-PDS/pds4-information-model/runs/6815107257?check_suite_focus=true#step:5:120), yes, I see an error message. However, one line above that shows that Maven returned exit code `0`, which means "success".

The Roundup action prints the exit status from the invoked process, followed by the captured standard output and standard error:
```python
_logger.debug('🏃‍♀️ Running «%r»', argv)
…
cp = subprocess.run(argv, stdin=subprocess.DEVNULL, capture_output=True, check=True)
_logger.debug('🏁 Run complete, rc=%d', cp.returncode)
_logger.debug('Stdout = «%s»', cp.stdout.decode('utf-8'))
_logger.debug('Stderr = «%s»', cp.stderr.decode('utf-8'))
```

The output shows the exit status = `0`:

![Screen Shot 2022-06-15 at 3 56 28 PM](https://user-images.githubusercontent.com/814813/173927896-2d3f3bcd-dbf8-49e8-818c-29c0e4366b51.png)

**Comment by jordanpadams** [comment]
@nutjob4life copy. very very weird... will close as wontfix for now, and monitor closely.

thing is, somewhere in this release, the documentation definitely did not generate or deploy successfully because the site was not generated correctly. but 🤷

**Comment by nutjob4life** [comment]
Thanks @jordanpadams—a little perplexing, and that leaves a kind of mental hangnail in the back of my cerebellum.

But that's a good thing, because if it happens again, we might find some commonalities and—better yet—causes 😉

**Comment by jordanpadams** [comment]
@nutjob4life looks like this continues to happen: https://github.com/NASA-PDS/pds4-information-model/runs/6942861159?check_suite_focus=true#step:5:270 

also part of a bigger issue with the PDS4 IM repo and the GPG plugin. no idea what is going on here (works on my laptop). I am curious if any other nested repo works with GPG or not. not a big deal right now, but not ideal trying to build/release this 12 times and the tagging still goes through, but the documentation doesn't work because the deploy step fails before the docs are built.
