### ISSUE TITLE
Java SNAPSHOT versions still have {hotfix} number

### ISSUE THREAD

**Issue by jordanpadams** [NASA-PDS/roundup-action#86]
## 🐛 Describe the bug

It doesn't look like the upgrade for https://github.com/NASA-PDS/roundup-action/issues/81 works as expected for Java tags. See https://github.com/NASA-PDS/validate/releases to see 2.2.4-SNAPSHOT

**Comment by tloubrieu-jpl** [comment]
It can not be reproduced
