### ISSUE TITLE
Improve release tagging in roundup

### ISSUE THREAD

**Issue by jordanpadams** [NASA-PDS/roundup-action#90]
## 💡 Description

Instead of triggering on update to release branch
- [ ] trigger on tag `release/x.x.x`
- [ ] update changelog/requirements/etc.
- [ ] re-tag at HEAD
- [ ] push out release

**Comment by jordanpadams** [comment]
note: not expected to be completed this Sprint.

**Comment by jordanpadams** [comment]
Status: @nutjob4life got everything setup in the sandbox

**Comment by nutjob4life** [comment]
Ideas:
- After the re-tag at HEAD, delete the release/1.2.3 tag (may not be necessary thanks to prune force)
- Check if it's a stable workflow but triggered by a branch push instead of a tag push and bail early

**Comment by jimmie** [comment]
python side is done
java/mvn side is being a beast
