### ISSUE TITLE
Roundup failing on unstable build

### ISSUE THREAD

**Issue by jordanpadams** [NASA-PDS/roundup-action#96]
## 🐛 Describe the bug

Unstable build failing

## 📜 To Reproduce
1. Go to Validate repo (or I imagine a lot of our repos)
2. Try to push to main to trigger unstable roundup

## 🕵️ Expected behavior

Builds successfully

## 📚 Version of Software Used

stable

## 🩺 Test Data / Additional context

https://github.com/NASA-PDS/validate/actions/runs/3200657350/jobs/5227818080

---

## ⚙️ Engineering Details
It looks like we are trying to pull the `release/*` tags here: https://github.com/NASA-PDS/roundup-action/blob/fa2d51156697b734ea1e477a03d25c16914a39c2/src/pds/roundup/step.py#L90 . And `git describe` fails if none exist.

That being said, should we really be looking for the `release/*` tags? We remove those after we create an actual tag, so we should really get the latest tag number and then increment that accordingly, no?

**Comment by nutjob4life** [comment]
@jordanpadams it looks like the old behavior for changelog generation was to do `git branch --show-current` and use its output for the changelog's future release number ([see the diff](https://github.com/NASA-PDS/roundup-action/pull/91/files#diff-2083bea00e7ed9a82b41200c4fd86204a2670ad7c39b1436f71bed291615224eL89)). I can bring that back.

Do we want changelog generation on unstable releases too, though? Maybe the better fix is to skip changelogs on unstables? What do you think?

**Comment by jordanpadams** [comment]
@nutjob4life I think we should still do changelog for unstable so folks can see what has been updated in the current snapshot. That being said, how will you then know its a snapshot version of you are on main?

**Comment by nutjob4life** [comment]
Basically the same way as before, but detecting if the `git describe` fails
