### ISSUE TITLE
git push in roundup action failing w/ remote ahead of local

### ISSUE THREAD

**Issue by jimmie** [NASA-PDS/roundup-action#98]
## 🐛 Describe the bug
Trying to build harvest release/3.7.1 and roundup-action failed with following error:

> 1 file changed, 1 insertion(+), 1 deletion(-)
> DEBUG:pds.roundup.util:Stderr = «»
> DEBUG:pds.roundup.util:🏃‍♀️ Running «['git', 'push', 'origin', 'HEAD:main']»
> CRITICAL:pds.roundup.util:💥 Process with command line ['git', 'push', 'origin', 'HEAD:main'] failed with status 1
> CRITICAL:pds.roundup.util:🪵 Stdout = «»
> CRITICAL:pds.roundup.util:📚 Stderr = «To https://github.com/NASA-PDS/harvest
>  ! [rejected]        HEAD -> main (fetch first)
> error: failed to push some refs to 'https://github.com/NASA-PDS/harvest'
> hint: Updates were rejected because the remote contains work that you do
> hint: not have locally. This is usually caused by another repository pushing
> hint: to the same ref. You may want to first integrate the remote changes
> hint: (e.g., 'git pull ...') before pushing again.
> hint: See the 'Note about fast-forwards' in 'git push --help' for details.
> »
> Traceback (most recent call last):
>   File "/usr/local/lib/python3.9/site-packages/pds.roundup-0.0.0-py3.9.egg/pds/roundup/util.py", line 52, in invoke
>   File "/usr/local/lib/python3.9/subprocess.py", line 528, in run
>     raise CalledProcessError(retcode, process.args,
> subprocess.CalledProcessError: Command '['git', 'push', 'origin', 'HEAD:main']' returned non-zero exit status 1.

Could be a side effect of [#76](https://github.com/NASA-PDS/roundup-action/issues/76).

**Comment by jordanpadams** [comment]
setting severity to low for the time being unless it becomes a major problem moving forward. I think this usually just means you are tagging without the latest commit. I have noticed this happening when I merge a PR and then try to tag a release before the unstable build completes. The unstable build then sneaks in a change log update before the stable build completes.

**Comment by jordanpadams** [comment]
@nutjob4life @jimmie FYI ☝️

**Comment by jimmie** [comment]
I am OK with kicking this to the curb.

**Comment by nutjob4life** [comment]
Over Slack, @jimmie wrote:

> it seems we can reproduce that build error fairly easily - each time we’ve done a commit just before tagging - the subsequent build appears to fail  consistently. Food for thought.

So not kicking this to the curb.

**Comment by nutjob4life** [comment]
The following repositories have pull requests pending may address the mutex (but may also have [overlap with this issue](https://github.com/NASA-PDS/software-issues-repo/issues/41)):

-   [archive-analytics](https://github.com/NASA-PDS/archive-analytics)
-   [deep-archive](https://github.com/NASA-PDS/deep-archive)
-   [doi-service](https://github.com/NASA-PDS/doi-service)
-   [doi-ui](https://github.com/NASA-PDS/doi-ui)
-   [feedback-widget](https://github.com/NASA-PDS/feedback-widget)
-   [github-actions-base](https://github.com/NASA-PDS/github-actions-base)
-   [harvest](https://github.com/NASA-PDS/harvest)
-   [mi-label](https://github.com/NASA-PDS/mi-label)
-   [naif-pds4-bundler](https://github.com/NASA-PDS/naif-pds4-bundler)
-   [nasa-pds.github.io](https://github.com/NASA-PDS/nasa-pds.github.io)
-   [pds-api](https://github.com/NASA-PDS/pds-api)
-   [pds-api-pythonlib](https://github.com/NASA-PDS/pds-api-pythonlib)
-   [pds-api-service](https://github.com/NASA-PDS/pds-api-service)
-   [pds-github-util](https://github.com/NASA-PDS/pds-github-util)
-   [PDS-Pipelines](https://github.com/NASA-PDS/PDS-Pipelines)
-   [pds-registry-app](https://github.com/NASA-PDS/pds-registry-app)
-   [pds-view](https://github.com/NASA-PDS/pds-view)
-   [pds3-product-tools](https://github.com/NASA-PDS/pds3-product-tools)
-   [pds4-graph](https://github.com/NASA-PDS/pds4-graph)
-   [pds4-information-model](https://github.com/NASA-PDS/pds4-information-model)
-   [pds4-jparser](https://github.com/NASA-PDS/pds4-jparser)
-   [pdsen-corral](https://github.com/NASA-PDS/pdsen-corral)
-   [pdsen-maven-parent](https://github.com/NASA-PDS/pdsen-maven-parent)
-   [PLAID](https://github.com/NASA-PDS/PLAID)
-   [product_relationships](https://github.com/NASA-PDS/product_relationships)
-   [registry-api](https://github.com/NASA-PDS/registry-api)
-   [registry-common](https://github.com/NASA-PDS/registry-common)
-   [registry-crawler-service](https://github.com/NASA-PDS/registry-crawler-service)
-   [registry-harvest-cli](https://github.com/NASA-PDS/registry-harvest-cli)
-   [registry-harvest-service](https://github.com/NASA-PDS/registry-harvest-service)
-   [registry-loader](https://github.com/NASA-PDS/registry-loader)
-   [registry-mgr](https://github.com/NASA-PDS/registry-mgr)
-   [roundup-action](https://github.com/NASA-PDS/roundup-action)
-   [sumo-tools](https://github.com/NASA-PDS/sumo-tools)
-   [supplementer](https://github.com/NASA-PDS/supplementer)
-   [template-repo-java](https://github.com/NASA-PDS/template-repo-java)
-   [template-repo-python](https://github.com/NASA-PDS/template-repo-python)
-   [tracking-service](https://github.com/NASA-PDS/tracking-service)
-   [transform](https://github.com/NASA-PDS/transform)
-   [wds-react](https://github.com/NASA-PDS/wds-react)
-   [wds-web](https://github.com/NASA-PDS/wds-web)
-   [wds-wordpress](https://github.com/NASA-PDS/wds-wordpress)
-   [web-analytics](https://github.com/NASA-PDS/web-analytics)
-   [validate](https://github.com/NASA-PDS/validate)

**Comment by jordanpadams** [comment]
all PRs merged. done!
